Update 4.md
nftalliance/docs pull request #29
Opened 2022-04-22 16:31 UTC by com-master

Make storage better

2022-04-25 17:40 UTC, kokkekpek requested changes
Proposals:
* Move back `gasReceiver`
* Use `string encoding`

2022-04-25 17:40 UTC, kokkekpek commented on src/Standard/TIP-4/4.md
> +    function fill(uint32 id, bytes chunk) external;
`uint8` > `uint32` is good ✅

Removing `address gasReceiver` is bad ❌
`gasReceiver` is required for internal messages. Need to know where to send remaining gas after each transaction. Example:
* Balance of `Storage` contract is **0.1 EVER**
* Call `fill()` with **1 EVER** using internal message **first time**. **0.1 EVER** spend for fee fee. **0.9 EVER** back to `gasReceiver`
* Call `fill()` with **1 EVER** using internal message **last time**. **0.1 EVER** spend for fee. **0.9 EVER** back to `gasReceiver`
* Balance of `Storage` contract still is **0.1 EVER**

`gasReceiver` is also required for external messages. Need to know where to send remaining gas from Storage contract balance each last `fill()` call. Example:
* Balance of `Storage` contract is **1 EVER**
* Call `fill()` with using external message **first time**. **0.1 EVER** spend for fee fee. * Balance of `Storage` contract is **0.9 EVER**
* Call `fill()` with using external message **last time**. **0.1 EVER** spend for fee. **0.7 EVER** back to `gasReceiver`
* Balance of `Storage` contract still is **0.1 EVER**

2022-04-25 17:40 UTC, kokkekpek commented on src/Standard/TIP-4/4.md
> +        bool zstdEncoding,
I think `bool` value is wrong. Compression method may differ from zstd. In my opinion, a good solution would be to use a `string`, as is done in [HTTP header Content-Encoding](https://developer.mozilla.org/ru/docs/Web/HTTP/Headers/Content-Encoding)

2022-05-12 16:29 UTC, closed without merging

2022-05-12 16:29 UTC, com-master commented
Was moved to https://github.com/nftalliance/docs/pull/34